# Generated by Django 3.2.6 on 2021-08-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='hashtag',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='speed',
            field=models.IntegerField(default=120),
        ),
    ]
