# Generated by Django 3.2.6 on 2021-08-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0005_sound_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='track1',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track10',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track11',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track12',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track13',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track14',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track15',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track16',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track2',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track3',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track4',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track5',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track6',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track7',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track8',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track9',
            field=models.CharField(default='', max_length=4),
        ),
    ]
