# Generated by Django 3.2.6 on 2021-08-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0006_auto_20210812_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='speed',
        ),
    ]
