# Generated by Django 3.2.6 on 2021-08-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0007_remove_sound_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='place',
            field=models.CharField(default='', max_length=13),
        ),
    ]
