# Generated by Django 3.2.4 on 2021-08-27 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0008_alter_sound_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach', models.FileField(blank=True, null=True, upload_to='mp3/', validators=[django.core.validators.FileExtensionValidator(['mp3'])], verbose_name='mp3ファイル')),
            ],
        ),
    ]
