# Generated by Django 3.2.4 on 2021-09-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0009_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='track16',
            field=models.CharField(default='', max_length=50),
        ),
    ]
