# Generated by Django 3.2.6 on 2021-09-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0010_alter_sound_track16'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='track16',
            field=models.CharField(default='empty', max_length=7),
        ),
    ]
