# Generated by Django 3.2.6 on 2021-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0011_alter_sound_track16'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sound',
            name='bpm',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='chat',
            name='hashtag',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sound',
            name='place',
            field=models.CharField(default='-', max_length=13),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track1',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track10',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track11',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track12',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track13',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track14',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track15',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track2',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track3',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track4',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track5',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track6',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track7',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track8',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track9',
            field=models.CharField(default='-', max_length=4),
        ),
    ]
