# Generated by Django 3.2.6 on 2021-09-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0012_auto_20210912_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='track14',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='track15',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='track16',
        ),
        migrations.AlterField(
            model_name='sound',
            name='track13',
            field=models.CharField(default='noiseEmpty', max_length=13),
        ),
    ]
