# Generated by Django 3.2.6 on 2021-11-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0014_alter_sound_track13'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='place',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='track13',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='track4',
        ),
        migrations.AlterField(
            model_name='chat',
            name='hashtag',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='sound',
            name='comment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track10',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track11',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track12',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track5',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track6',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track7',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track8',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track9',
            field=models.CharField(default='', max_length=10),
        ),
    ]
