# Generated by Django 3.2.6 on 2021-11-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0015_auto_20211110_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='bpm',
            new_name='speed',
        ),
        migrations.RenameField(
            model_name='sound',
            old_name='track10',
            new_name='track4',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='track11',
        ),
        migrations.RemoveField(
            model_name='sound',
            name='track12',
        ),
    ]
