# Generated by Django 3.2.9 on 2021-11-21 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0018_auto_20211121_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sound',
            old_name='place',
            new_name='beats',
        ),
        migrations.AlterField(
            model_name='sound',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 21, 15, 53, 38, 904527)),
        ),
    ]
