# Generated by Django 3.2.9 on 2021-11-23 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0019_auto_20211121_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='username',
            new_name='contribution',
        ),
        migrations.AlterField(
            model_name='sound',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 23, 13, 40, 25, 562269)),
        ),
    ]
