# Generated by Django 3.2.9 on 2021-12-01 05:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0021_alter_sound_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 12, 1, 14, 44, 28, 765230))),
            ],
        ),
        migrations.RemoveField(
            model_name='sound',
            name='date',
        ),
        migrations.AddField(
            model_name='account',
            name='icon',
            field=models.ImageField(default='Dynamusic\\static\\img\\default_icon.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='chat',
            name='sound',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dynamusic.sound'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='comment',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track1',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track2',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track3',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track4',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track5',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track6',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track7',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track8',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track9',
            field=models.CharField(default='', max_length=5),
        ),
    ]
