# Generated by Django 3.2.9 on 2021-12-01 05:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0022_auto_20211201_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sound',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Dynamusic.sound'),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 14, 44, 54, 265410)),
        ),
    ]
