# Generated by Django 3.2.9 on 2021-12-01 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0023_auto_20211201_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 14, 45, 50, 36135)),
        ),
    ]
