# Generated by Django 3.2.9 on 2021-12-01 05:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0024_alter_information_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Dynamusic.sound'),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 14, 48, 18, 226954)),
        ),
    ]
