# Generated by Django 3.2.9 on 2021-12-01 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0027_alter_information_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='midi',
            name='filename',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 15, 58, 28, 501407)),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 15, 58, 28, 501407)),
        ),
    ]
