# Generated by Django 3.2.9 on 2021-12-08 08:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0030_auto_20211204_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dynamusic.account'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 17, 13, 11, 52450)),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 8, 17, 13, 11, 51423)),
        ),
    ]
