# Generated by Django 3.2.9 on 2021-12-15 05:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0031_auto_20211208_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dynamusic.account'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 14, 31, 49, 758438)),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 14, 31, 49, 757438)),
        ),
    ]
