# Generated by Django 3.2.9 on 2021-12-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0032_auto_20211211_1959'),
        ('Dynamusic', '0036_auto_20211215_1446'),
    ]

    operations = [
    ]
