# Generated by Django 3.2.9 on 2021-12-20 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0042_alter_chat_time_alter_information_date'),
        ('Dynamusic', '0042_auto_20211218_1645'),
    ]

    operations = [
    ]
