# Generated by Django 3.2.9 on 2021-12-20 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0043_merge_20211220_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='contribution',
            new_name='edited',
        ),
        migrations.AddField(
            model_name='sound',
            name='bpm',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='sound',
            name='length',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 14, 40, 32, 962251)),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 20, 14, 40, 32, 961583)),
        ),
        migrations.AlterField(
            model_name='sound',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
