# Generated by Django 3.2.9 on 2021-12-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0044_alter_chat_time_alter_information_date'),
        ('Dynamusic', '0045_auto_20211220_2053'),
    ]

    operations = [
    ]
