# Generated by Django 4.0 on 2021-12-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0045_auto_20211220_2053'),
        ('Dynamusic', '0047_alter_chat_time_alter_information_date'),
    ]

    operations = [
    ]
