# Generated by Django 3.2.9 on 2021-12-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0046_merge_20211221_1833'),
        ('Dynamusic', '0048_merge_20211221_2309'),
    ]

    operations = [
    ]
