# Generated by Django 3.2.6 on 2021-12-22 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0043_auto_20211222_1441'),
        ('Dynamusic', '0049_merge_20211222_0944'),
    ]

    operations = [
    ]
