# Generated by Django 3.2.9 on 2022-01-05 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0050_merge_20211222_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 2, 6, 35, 477510)),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 2, 6, 35, 476510)),
        ),
        migrations.AlterField(
            model_name='sound',
            name='length',
            field=models.FloatField(default=1),
        ),
    ]
