# Generated by Django 3.2.9 on 2022-01-05 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0051_auto_20220106_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 2, 9, 26, 833037)),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 2, 9, 26, 832040)),
        ),
    ]
