# Generated by Django 3.2.9 on 2022-01-05 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0052_auto_20220106_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 3, 42, 56, 640138)),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track3',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track4',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track5',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track6',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track7',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track8',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sound',
            name='track9',
            field=models.CharField(default='', max_length=20),
        ),
    ]
