# Generated by Django 3.2.6 on 2022-01-06 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0053_auto_20220106_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 6, 23, 38, 53, 346321)),
        ),
    ]
