# Generated by Django 3.2.9 on 2022-01-09 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0056_alter_chat_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 6, 13, 6, 557267)),
        ),
    ]
