# Generated by Django 3.2.9 on 2022-01-13 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0058_auto_20220110_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='guest',
            field=models.CharField(default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 19, 51, 11, 779484)),
        ),
    ]
