# Generated by Django 3.2.9 on 2022-01-12 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0058_auto_20220110_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 1, 11, 46, 389690)),
        ),
    ]
