# Generated by Django 3.2.9 on 2022-01-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamusic', '0060_alter_chat_time'),
        ('Dynamusic', '0063_alter_chat_time'),
    ]

    operations = [
    ]
